### ISSUE TITLE
Suggestion: Add volume adjuster

### ISSUE THREAD

**Issue by Deraj34** [zealsprince/lc-locker#2]
The Locker is _very_ loud by default. Which is great for being spooky and making you jump, but it might be too loud, and a volume adjustment in the config would help this.

**Comment by zealsprince** [comment]
Agree. I like it at the loudness that it is but I'll add an option to reduce it! Will do that in the update where I add level spawn selection and expand the config!

**Comment by zealsprince** [comment]
Completed as of [afac220](https://github.com/zealsprince/lc-locker/commit/afac22083e6b2a86923bf471163f286ad580f4ed)!
