### ISSUE TITLE
Game crashes with modded doors

### ISSUE THREAD

**Issue by Hambergerrr** [zealsprince/lc-locker#4]
While testing the mod out and seeing how the locker interacts with certain maps and layouts, I found out that if the door can't be broken and/or has a unique opening animation (such as the doors on secret labs), the locker will attempt to open the door just like any other mob would. However, since the locker has a strength value of 0 when trying to open the door, it ends up failing, and immediately tries to open the door again. This causes a quick loop that floods the console, and causes the game to crash.

While I doubt this issue is a problem for those who play with unmodded interiors, it might still need to be looked into just in the off chance a locker slams close enough to a door without destroying it that it tries to open the door, causing a similar issue.

**Comment by zealsprince** [comment]
Going to check this later and attempt to replicate it! Thanks for the report!

**Comment by zealsprince** [comment]
This has been fixed as of b3a8c92!
