### ISSUE TITLE
Not able to get Locker spawning on custom moons.

### ISSUE THREAD

**Issue by bigpak2456** [zealsprince/lc-locker#5]
![image](https://github.com/zealsprince/lc-locker/assets/116227014/a7f1581c-ff0d-4902-849b-470643e2bf23)
![image](https://github.com/zealsprince/lc-locker/assets/116227014/bebbe494-b52f-4220-92da-4f1e805a32a5)
![image](https://github.com/zealsprince/lc-locker/assets/116227014/eb6f55fc-7602-497b-955c-8f99fc05ce2d)

for example, with these settings provided, I have been unable to get the lockers to spawn naturally on these maps, tried changing up spawn weights etc, but in the logs I am unable to find any mention of lockers spawning on these custom maps, but they do spawn on offense for example. Any ideas?

**Comment by zealsprince** [comment]
I think that lonely `3000` before Poltergust might be the problem?
