### ISSUE TITLE
.blend file does not have textures

### ISSUE THREAD

**Issue by HameleoNew** [zealsprince/lc-locker#8]
In blender, model change its textures on pink ones. 
![Снимок экрана 2024-04-29 231339](https://github.com/zealsprince/lc-locker/assets/86353243/f834f4fa-782b-454c-aec6-27e5b00072cd)

**Comment by zealsprince** [comment]
Fixed as of https://github.com/zealsprince/lc-locker/commit/fb64b9a4e9eef48402d9d0431ef08c10665010cb! I've added all assets and resources to a new `Assets` folder. Includes Unity prefabs required for building the asset bundle as well. You can find the updated Blender model with packed textures in the `Blender` sub-directory.
