### ISSUE TITLE
cannot make locker spawn on specific moons

### ISSUE THREAD

**Issue by rootbeer2222** [zealsprince/lc-locker#9]
basically I want to use the moon list and only make the locker spawn on A to S level moons but even with spawn chance set to 0 but 25000 in the moons list it never spawns unless I have all in level set to all with 25000 spawn chance and even if I put the level set to the names of the moons and 25000 weight.

**Comment by zealsprince** [comment]
Can you share the spawn rates from your configuration?

**Comment by rootbeer2222** [comment]
[lockercfg.txt](https://github.com/user-attachments/files/15862402/lockercfg.txt)
mind you if I have the spawn weight at something high the locker will spawn but will spawn on all moons and ignore the list

**Comment by zealsprince** [comment]
Closing the issue as it's become stale and I haven't been able to replicate this - neither has the community.
